server:
  port: 9090
  servlet:
    context-path: /newBlog
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      # 实体类有更新时，数据库表更新
      ddl-auto: update
    show-sql: true
    format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    # 过滤字符编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    host: smtp.163.com
    username: 13002518187@163.com
    password: wangyi123
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
  jackson:
    default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段
  swagger:
    enabled: true
    base-package: com.wy.newblog
jasypt:
  encryptor:
    password: 123456


