server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.151.23:3306/blog?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          log-slow-sql: true
      stat-view-servlet:
       # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: blog
        login-password: blog
        # 白名单，多个使用逗号隔开
        allow:
        # 黑名单
        deny:
  rabbitmq:
    host: www.dbbaxbb.cn
    port: 5672
    username: guest
    password: guest
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  redis:
    port: 6379
    host: 47.94.151.23
    password: 123456
    database: 1
    timeout: 5s
    jedis:
      pool:
        max-active: 8
        max-idle: 50
        min-idle: 0
        max-wait: -1ms
mybatis:
  mapper-locations: classpath*:**/*Mapper.xml