server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.151.23:3306/blog
    username: root
    password: yourPassword
  rabbitmq:
    host: 47.94.151.23
    port: 5672
    username: guest
    password: guest
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  redis:
    port: 6379
    host: 47.94.151.23
    password: 123456
    database: 1
    timeout: 1s
    jedis:
      pool:
        max-active: 8
        max-idle: 50
        min-idle: 0
        max-wait: -1ms